//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientcompany
    {
        public long id { get; set; }
        public string name_company { get; set; }
        public string address { get; set; }
        public int telephone { get; set; }
        public string email { get; set; }
        public string Domain { get; set; }
        public string logotipo { get; set; }
    }
}
