//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class condition_instruction
    {
        public string and_or_condition { get; set; }
        public int number_order { get; set; }
        public int id_condition { get; set; }
        public string condition_instruction1 { get; set; }
        public int column_excel { get; set; }
        public int id_formula { get; set; }
    }
}
