//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class formula
    {
        public int id_formula { get; set; }
        public string name_formula { get; set; }
        public int id_tag { get; set; }
        public string method { get; set; }
    
        public virtual tag tag { get; set; }
    }
}
