//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCliente
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projetoEntities : DbContext
    {
        public projetoEntities()
            : base("name=projetoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientcompany> clientcompanies { get; set; }
        public virtual DbSet<column_excel> column_excel { get; set; }
        public virtual DbSet<condition_instruction> condition_instruction { get; set; }
        public virtual DbSet<formula> formulae { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<template> templates { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<spreadsheet> spreadsheets { get; set; }
    }
}
